version: '3'
services:
  selenium-chrome:
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./music:/app/music
    command: ["bash", "run.sh"]
    networks:
      - mynetwork

networks:
  mynetwork: